---
- name: Install Jenkins 2.546 on Rocky Linux
  hosts: vps
  become: yes
  vars:
    jenkins_port: 8080

  tasks:
    - name: Ensure epel-release is installed
      dnf:
        name: epel-release
        state: present

    - name: Install required dependencies (Java, fontconfig, wget)
      dnf:
        name:
          - fontconfig
          - java-21-openjdk
          - wget
        state: present

    - name: Add Jenkins weekly repository
      get_url:
        url: https://pkg.jenkins.io/redhat/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins GPG key for 2026 releases
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io-2026.key

    - name: Upgrade system packages
      dnf:
        name: '*'
        state: latest

    - name: Install Jenkins
      dnf:
        name: jenkins
        state: present

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Open Jenkins port in firewall
      firewalld:
        port: "{{ jenkins_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
    - name: Display initial Jenkins admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
    - name: Show Jenkins admin password
      debug:
        msg: "Initial Jenkins Admin Password: {{ jenkins_password.stdout }}"
  handlers:
    - name: Restart Jenkins
      systemd:
        name: jenkins
        state: restarted