---
- name: Install essential packages
  dnf:
    name:
      - python3
      - python3-pip
      - python3-devel
      - git
      - curl
      - wget
      - vim
      - nano
      - bash-completion
      - bind-utils
      - net-tools
      - socat
      - conntrack
      - iproute-tc
      - htop
      - tree
      - tmux
      - make
      - gcc
      - gcc-c++
      - openssl-devel
      - libffi-devel
      - zlib-devel
      - bzip2-devel
      - readline-devel
      - sqlite-devel
      - xz-devel
      - ncurses-devel
      - epel-release
      - rsync
      - unzip
      - tar
      - gnupg2
      - ca-certificates
      - lsof
      - jq
      - gettext
    state: present
    update_cache: yes

- name: Ensure pip is installed
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install yamllint via pip
  ansible.builtin.pip:
    name: yamllint