---
- name: Download k9s binary
  get_url:
    url: "https://github.com/derailed/k9s/releases/download/v{{ versions.k9s }}/k9s_Linux_{{ architecture }}.tar.gz"
    dest: /tmp/k9s.tar.gz

- name: Extract k9s
  unarchive:
    src: /tmp/k9s.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/k9s

- name: Set executable permission for k9s
  file:
    path: /usr/local/bin/k9s
    mode: "0755"
