- import_tasks: helm.yml
  when: "'helm' in devops_tools_enabled"

- import_tasks: helmfile.yml
  when: "'helmfile' in devops_tools_enabled"

- import_tasks: kustomize.yml
  when: "'kustomize' in devops_tools_enabled"

- import_tasks: tilt.yml
  when: "'tilt' in devops_tools_enabled"

- import_tasks: kluctl.yml
  when: "'kluctl' in devops_tools_enabled"

- import_tasks: argocd.yml
  when: "'argocd' in devops_tools_enabled"

- import_tasks: stern.yml
  when: "'stern' in devops_tools_enabled"

- import_tasks: k9s.yml
  when: "'k9s' in devops_tools_enabled"

- import_tasks: kubectx.yml
  when: "'kubectx' in devops_tools_enabled"

- import_tasks: skaffold.yml
  when: "'skaffold' in devops_tools_enabled"

- import_tasks: talosctl.yml
  when: "'talosctl' in devops_tools_enabled"
