# Default enabled tools
devops_tools_enabled:
  - awscli
  - terraform
  - vault
  - helm
  - helmfile
  - kubectl
  - kustomize
  - k9s
  - tilt
  - stern
  - kubeseal
  - sops
  - dive
  - lazydocker
  - hadolint
  - trivy
  - ansible_lint
  - common_packages
  - kluctl
  - argocd
  - kubectx
  - skaffold
  - talosctl

# Disabled by default
# - minikube
# - sonobuoy
# - ytt
# - goss
# - checkov
# - molecule
# - testinfra

# GitOps tool versions
